const express = require("express");
const c = require("../controllers/auth.controller");
const protect = require("../middleware/auth.middleware");
const router = express.Router();
router.post("/register", c.registerUser);
router.post("/login", c.loginUser);
router.post("/logout", c.logoutUser);
router.get("/me", protect, c.getMe);
router.patch("/profile", protect, c.updateProfile);
router.patch("/password", protect, c.changePassword);
router.get("/addresses", protect, c.listAddresses);
router.post("/addresses", protect, c.addAddress);
router.patch("/addresses/:addressId", protect, c.updateAddress);
router.delete("/addresses/:addressId", protect, c.deleteAddress);
router.patch("/addresses/:addressId/default", protect, c.setDefaultAddress);
router.get("/wishlist", protect, c.getWishlist);
router.patch("/wishlist/:productId", protect, c.toggleWishlist);
router.post("/recently-viewed/:productId", protect, c.addRecentlyViewed);
router.get("/recently-viewed", protect, c.getRecentlyViewed);
router.patch("/preferences", protect, c.updatePreferences);
router.post("/deletion-request", protect, c.requestDeletion);
router.get("/activity", protect, c.getActivity);
module.exports = router;
